### ISSUE TITLE
Implementar todos los `BinOp`s

### ISSUE THREAD

**Issue by VctorAHernndez** [humberto-ortiz/compilers-s2021#14]
Todo lo que tenía que ver con `BinOp`s ya no existe :(

Lo único que queda son [estas últimas líneas comentadas](https://github.com/humberto-ortiz/compilers-s2021/blob/6367f2b3aafba7996815240a7588eae25789413d/bools/parser.mly#L35).

Habría que implementar `+`, `-` y `*`.

**Comment by ErnestoOrtiz2** [comment]
Yo los tengo. Pronto los mando.

**Comment by humberto-ortiz** [comment]
Ernesto implemento los binop.
