### ISSUE TITLE
Crear Print con EPrim1

### ISSUE THREAD

**Issue by onielm** [humberto-ortiz/compilers-s2021#7]
Print no esta implementado. La implementacion debe ser con EPrim1. Aqui hay un link al codigo donde se utiliza EPrint1 con Add1, ya que seria algo similar para Print.

https://github.com/humberto-ortiz/compilers-s2021/blob/25e6981e4904b5058d403797ebb1a98fc5154c0a/bools/compiler.ml#L188

**Comment by VctorAHernndez** [comment]
Should be closed with 69fced6f6d98e4ffa22a27e4afab2bcbbcf1939f.
